### ISSUE TITLE
Simple Autoencoder & UBER Autoencoder notebook refers to functions and structures not declared

### ISSUE THREAD

**Issue by juhariis** [vincekellner/demandforecasting#1]
In section "Start Training of Models" / "Vanilla Auroencoder" *ts_largest* has not been defined when called

`ts_series_09_11_area237 = ts_largest['2009':'2011'].iloc[:,0].copy()
`

Perhaps one should have created that earlier when creating ts_10largest and ts_20largest?

The function used below has not been defined.

`all_results_batch512_drop03_W24_area237__2011 = get_full_autoencoder_pred_model_2H_128_32(ts_series_09_11_area237, multivariate, row_train_test_split, n_timesteps, n_features, stacked_encoder, n_batch_size_autoencoder, n_batch_size_pred_model, dropout_rate, n_epochs, model_name)
`

Furthermore, the csv file referred to in the notebook does not have the same name as the one in the repo.

I presume the repo is under active further development and you are aware of internal inconsistencoes? Anyway, it looks very interesting project, Good luck!

**Comment by vincekellner** [comment]
Hi, thank you for your helpful suggestions. I've updated the code and uploaded the missing csv-files.
